Portalia/ViewModels/DocumentViewModel.cs
using System.Collections.Generic;
using Portalia.Core.Entity;
using Portalia.Core.Enum;
using FolderType = Portalia.Core.Enum.FolderType;

namespace Portalia.ViewModels
{
    public class DocumentViewModel
    {
        public DocumentViewModel()
        {
            Documents = new List<Document>();
        }
        public FolderType FolderType { get; set; }
        public List<Document> Documents { get; set; }
        public string UserId { get; set; }
        public int? ProposalId { get; set; }
    }
}

Portalia/ViewModels/ProposalViewModel.cs
namespace Portalia.ViewModels
{
    public class ProposalViewModel
    {
        public int ProposalId { get; set; }
        public string ProposalTypeName { get; set; }
        public int FolderTypeId { get; set; }
    }
}

Portalia/ViewModels/Proposals/ProposalDetailViewModel.cs
using Portalia.Core.Enum;

namespace Portalia.ViewModels.Proposals
{
    public class ProposalDetailViewModel
    {
        public int ProposalId { get; set; }
        public string UserId { get; set; }
        public bool CanSeeMenu { get; set; }
        public bool CanSeeContract { get; set; }
        public string EmployeeStatus { get; set; }
        public bool IsEmployee { get; set; }

        public DocumentViewModel Document { get; set; } = new DocumentViewModel();
    }
}

Portalia/Controllers/DocumentController.cs
using System;
using System.Configuration;
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using nClam;
using Newtonsoft.Json;
using Portalia.Core.Entity;
using Portalia.Core.Enum;
using Portalia.Core.Interface.Service;
using Portalia.ViewModels;
using Repository.Pattern.Infrastructure;
using FolderType = Portalia.Core.Enum.FolderType;
using Portalia.Core.Dtos;
using Portalia.Core.Helpers;

namespace Portalia.Controllers
{
    public class DocumentController : BaseController
    {
        private readonly IDocumentService _documentService;
        private readonly IUserProfileAttributeService _profileAttributeService;
        private readonly IUserProfileService _userProfileService;
        private readonly IApplicationForm _applicationForm;
        private readonly IProposalService _proposalService;

        public DocumentController(
            IDocumentService documentService,
            IUserProfileAttributeService profileAttributeService,
            IUserProfileService userProfileService,
            IApplicationForm applicationForm,
            IProposalService proposalService)
        {
            _documentService = documentService;
            _profileAttributeService = profileAttributeService;
            _userProfileService = userProfileService;
            _applicationForm = applicationForm;
            _proposalService = proposalService;
        }

        public JsonResult DeleteDocument(Document document)
        {
            if (User.IsInRole(Roles.Administrator.ToString()) && !document.Proposal.UserId.IsNullOrWhiteSpace())
            {
                _documentService.Delete(document.DocumentId, document.Proposal.UserId);
            }
            else
            {
                _documentService.Delete(document.DocumentId, User.Identity.GetUserId());
            }

            return Json("", JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UploadFile(string userId, int proposalId, FolderType folderType)
        {

            var isSavedSuccessfully = true;
            var fName = "";
            var document = new Document();
            try
            {
                foreach (string fileName in Request.Files)
                {
                    var file = Request.Files[fileName];
                    if (file != null)
                    {
                        fName = file.FileName;
                        if (file.ContentLength > 0)
                        {
                            var target = new MemoryStream();
                            file.InputStream.CopyTo(target);
                            var data = target.ToArray();
                            var resultScan = await VirusScanner(data);
                            if (resultScan != ClamScanResults.Clean)
                            {
                                return Json(isSavedSuccessfully = false, JsonRequestBehavior.AllowGet);
                            }
                            document.FileBinary = data;
                            document.ProposalId = proposalId;
                            document.Name = file.FileName.Replace(" ", string.Empty);
                            document.FolderType = folderType;
                            _documentService.Create(document);
                            document.Proposal = new Proposal()
                            {
                                UserId = userId
                            };
                            document.FileBinary = null;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                isSavedSuccessfully = false;
            }

            return
                Json(isSavedSuccessfully
                    ? new { Message = fName, File = document }
                    : new { Message = "Error in saving file", File = document }, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UploadUserProfileFile(int userProfileId, int attributeDetailId,
            int userProfileAttributeId, string attributeName)
        {
            var isSavedSuccessfully = true;
            attributeName = attributeName.Replace(" ", String.Empty);
            var userProfileupload = new UploadUserProfileModel();
            var fName = "";
            try
            {
                foreach (string fileName in Request.Files)
                {
                    var file = Request.Files[fileName];

                    //Save file content goes here
                    fName = file.FileName;
                    fName = fName.Replace(" ", String.Empty);

                    if (file != null && file.ContentLength > 0)
                    {
                        var target = new MemoryStream();

                        file.InputStream.CopyTo(target);

                        var data = target.ToArray();
                        var resultScan = await VirusScanner(data);

                        if (resultScan != ClamScanResults.Clean)
                        {
                            return Json(isSavedSuccessfully = false, JsonRequestBehavior.AllowGet);
                        }

                        var storedFileName = $"{userProfileId}_{attributeDetailId}_{attributeName}_{fName}";
                        _profileAttributeService.UpdateAttribute(userProfileAttributeId, String.Empty, storedFileName,
                            data);
                        userProfileupload.UserProfileId = userProfileId;
                        userProfileupload.AttributeDetailId = attributeDetailId;
                        userProfileupload.UserProfileAttributeId = userProfileAttributeId;
                        userProfileupload.Name = storedFileName;
                        userProfileupload.AttributeName = attributeName;

                        //Transfer CV file to TOAST
                        if (attributeName == "CV")
                        {
                            var ex = default(Exception);
                            var userExtraInfo = _userProfileService.GetUserById(userProfileId);
                            var email = string.Empty;

                            email = userExtraInfo == default(AspNetUserExtraInfo) ? string.Empty : userExtraInfo.Email;

                            int applicationFormId =
                                _applicationForm.AddApplyForm(new ApplicationFormDto() {Email = email}, ex);

                            LoggerHelpers.Info($"ApplicationFormId: {applicationFormId}");

                            if (applicationFormId > 0)
                            {
                                var applicationDocumentDto = _applicationForm.CreateApplicationDocument(file, data, ex);

                                LoggerHelpers.Info(
                                    $"Serialize document object: {JsonConvert.SerializeObject(applicationDocumentDto)}");

                                if (applicationDocumentDto != null)
                                {
                                    var status = _applicationForm.AddApplyDocument(applicationFormId,
                                        applicationDocumentDto, ex);

                                    LoggerHelpers.Info($"Document Status: {status.ToString()}");

                                    if (status != AmarisEnum.SourcingStatus.WebsiteError)
                                    {
                                        var result =
                                            _applicationForm.UpdateApplicationFormStatus(applicationFormId,
                                                (int) status, ex);

                                        LoggerHelpers.Info($"Update ApplicationFormStatus Result: {result}");
                                    }
                                }
                            }

                            if (ex != default(Exception))
                            {
                                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                                LoggerHelpers.Error(ex);
                            }
                            
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                isSavedSuccessfully = false;
                LoggerHelpers.Error(ex);
            }

            return
                Json(isSavedSuccessfully
                    ? new {Message = fName, File = userProfileupload}
                    : new {Message = "Error in saving file", File = userProfileupload}, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteUserProfileDocument(UploadUserProfileModel document)
        {
            _profileAttributeService.UpdateAttribute(document.UserProfileAttributeId, String.Empty, null);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UploadUserPicture(string userId)
        {
            var isSavedSuccessfully = false;
            var fName = string.Empty;
            try
            {
                foreach (string fileName in Request.Files)
                {
                    var file = Request.Files[fileName];

                    //Save file content goes here
                    fName = file.FileName;
                    fName = fName.Replace(" ", String.Empty);
                    if (file != null && file.ContentLength > 0)
                    {
                        var target = new MemoryStream();
                        file.InputStream.CopyTo(target);
                        var data = target.ToArray();
                        var resultScan = await VirusScanner(data);
                        if (resultScan != ClamScanResults.Clean)
                        {
                            return Json(isSavedSuccessfully = false, JsonRequestBehavior.AllowGet);

Portalia/Views/Proposal/Create - Copy.cshtml
@model Portalia.ViewModels.CreateProposalViewModel
@section styles{
    @Styles.Render("~/Content/dropzonescss")
    <style>
        html, body {
            height: 100%;
        }

        #actions {
            margin: 2em 0;
        }
        /* Mimic table appearance */
        div.table {
            display: table;
        }

            div.table .file-row {
                display: table-row;
            }

                div.table .file-row > div {
                    display: table-cell;
                    vertical-align: top;
                    border-top: 1px solid #ddd;
                    padding: 8px;
                }

                div.table .file-row:nth-child(odd) {
                    background: #f9f9f9;
                }
        /* The total progress gets shown by event listeners */
        #total-progress {
            opacity: 0;
            transition: opacity 0.3s linear;
        }
        /* Hide the progress bar when finished */
        #previews .file-row.dz-success .progress {
            opacity: 0;
            transition: opacity 0.3s linear;
        }
        /* Hide the delete button initially */
        #previews .file-row .delete {
            display: none;
        }
        /* Hide the start and cancel buttons and show the delete button */
        #previews .file-row.dz-success .start,
        #previews .file-row.dz-success .cancel {
            display: none;
        }

        #previews .file-row.dz-success .delete {
            display: block;
        }
    </style>


}
<header id="head" class="secondary"></header>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="~/">Home</a></li>
        <li><a href="@Url.Action("Index","Proposal")">Project</a></li>
        <li class="active">Create</li>
    </ol>

    <div class="row">

        <!-- Article main content -->
        <article class="col-sm-9 maincontent">
            <header class="page-header">
                <h1 class="page-title">Create New Proposal</h1>
            </header>
            <p>
                We’d love to hear from you. Interested in working together? Fill out the form below with some info about your project and I will get back to you as soon as I can. Please allow a couple days for me to respond.
            </p>
            <br>
            @using (Html.BeginForm("Create", "Proposal", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-sm-12">
                        <label>Project Name</label>
                        @Html.TextBoxFor(m => m.ProjectName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ProjectName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-12">
                        <label>Client Name</label>
                        @Html.TextBoxFor(m => m.ClientName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ClientName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-12">
                        <label>Description</label>
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @placeholder = "Type your message here...", @rows = "5" })
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="container" id="container">
                            <div id="actions" class="row">

                                <div class="col-lg-7">
                                    <!-- The fileinput-button span is used to style the file input field as button -->
                                    <span class="btn btn-success fileinput-button">
                                        <i class="glyphicon glyphicon-plus"></i>
                                        <span>Add files...</span>
                                    </span>
                                    <button type="submit" class="btn btn-primary start">
                                        <i class="glyphicon glyphicon-upload"></i>
                                        <span>Start upload</span>
                                    </button>
                                    <button type="reset" class="btn btn-warning cancel">
                                        <i class="glyphicon glyphicon-ban-circle"></i>
                                        <span>Cancel upload</span>
                                    </button>
                                </div>

                                <div class="col-lg-5">
                                    <!-- The global file processing state -->
                                    <span class="fileupload-process">
                                        <div id="total-progress" class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                                            <div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress></div>
                                        </div>
                                    </span>
                                </div>
                            </div>
                            <div class="table table-striped files" id="previews">

                                <div id="template" class="file-row">
                                    <!-- This is used as the file preview template -->
                                    <div>
                                        <span class="preview"><img data-dz-thumbnail /></span>
                                    </div>
                                    <div>
                                        <p class="name" data-dz-name></p>
                                        <strong class="error text-danger" data-dz-errormessage></strong>
                                    </div>
                                    <div>
                                        <p class="size" data-dz-size></p>
                                        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                                            <div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress></div>
                                        </div>
                                    </div>
                                    <div>
                                        <button class="btn btn-primary start">
                                            <i class="glyphicon glyphicon-upload"></i>
                                            <span>Start</span>
                                        </button>
                                        <button data-dz-remove class="btn btn-warning cancel">
                                            <i class="glyphicon glyphicon-ban-circle"></i>
                                            <span>Cancel</span>
                                        </button>
                                        <button data-dz-remove class="btn btn-danger delete">
                                            <i class="glyphicon glyphicon-trash"></i>
                                            <span>Delete</span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 text-right">
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
                        <input class="btn btn-primary" type="submit" value="Create New">
                    </div>
                </div>
            }

        </article>
        <!-- /Article -->

    </div>
</div> <!-- /container -->
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/dropzonescripts")
}

Portalia/Views/Proposal/Create.cshtml
@using Portalia.Models
@using Portalia.Resources
@model Portalia.ViewModels.CreateProposalViewModel
<header id="head" class="secondary"></header>

<!-- container -->
<div class="container">
    <ol class="breadcrumb">
        <li><a href="~/">@Portalia.Resources.Proposal.Home</a></li>
        <li><a href="@Url.Action("Index","Proposal", new {userId = Model.UserId})">@Portalia.Resources.Proposal.Project</a></li>
        <li class="active">@Portalia.Resources.Proposal.Create</li>
    </ol>
    <div class="row">
        <!-- Article main content -->
        <article class="col-sm-9 maincontent">
            <header class="page-header">
                <h1 class="page-title">@Portalia.Resources.Proposal.Hello @User.Identity.GetFirstname()!</h1>
            </header>
            <br>
            @using (Html.BeginForm("Create", "Proposal", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.HiddenFor(c=>c.UserId)
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-sm-1">
                        <div class="round blue">
                            <span>1</span>
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <label>
                            <strong>@Portalia.Resources.Proposal.ProjectName</strong>
                        </label>
                        @Html.TextBoxFor(m => m.ProjectName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ProjectName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-1">
                        <div class="round blue">
                            <span>2</span>
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <label>@Portalia.Resources.Proposal.ClientName</label>
                        @Html.TextBoxFor(m => m.ClientName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ClientName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-1">
                        <div class="round blue">
                            <span>3</span>
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <label>@Proposal.Description</label>
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @placeholder = @Portalia.Resources.Proposal.TypeYourDescription, @rows = "5" })
                        @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-1">

                    </div>
                    <div class="col-sm-11 text-left">
                        <input class="btn btn-info" type="submit" value="@Portalia.Resources.Proposal.PostProjectNow">
                    </div>
                </div>
            }
        </article>
        <!-- /Article -->
    </div>
</div> <!-- /container -->
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Portalia/Views/Proposal/_CreateProposalWizard.cshtml
@using Microsoft.AspNet.Identity
@using Portalia.Core.Enum
@using Portalia.Resources
@model Portalia.Core.Entity.Proposal
@{
    Layout = null;
    var haveDocument = Model.Documents != null && Model.Documents.Any();
}

@Html.Hidden("CheckUserProfileValidationUrl", @Url.Action("CheckUserValidation", "Proposal", new { userId = Model.UserId }))
<div id="smartwizard">
    <input style="visibility: hidden" data-file-name="~/UserDocuments/@User.Identity.GetUserId()/Proposal_@Model." />
    <ul>
        <li><a href="#step-1">@string.Format(Proposal.Step, 1)<br /><small>@Proposal.DownLoadDocument</small></a></li>
        <li><a href="#step-2">@string.Format(Proposal.Step, 2)<br /><small>@Proposal.UploadDocument</small></a></li>
        <li><a href="#step-3">@string.Format(Proposal.Step, 3)<br /><small>Envoyer propostion</small></a></li>
    </ul>

    <div>
        <div id="step-1" class="">
            <div class="">
                <p class="bg-info">
                    Veuillez remplir le<a class="text-center" target="_black" href="@Url.Content("~/Content/Proposal/FichePreparative.pdf")">
                        <i class="fa fa-file"></i>document
                    </a>relatif à votre projet
                </p>
            </div>
        </div>
        <div id="step-2" class="">
            <form class="dropzone" id="upload-document" data-url="@Url.Action("UploadFile", "Document", new {folderType = FolderType.MyProject, proposalId = Model.ProposalId, userId = Model.UserId})" method="post" enctype="multipart/form-data"></form>
            <h5 style="display: @(haveDocument ? "block":"none")" id="user-project-documents">
                <a target="_black" href="@Url.Action("Detail","Proposal",new { proposalId = Model.ProposalId })">
                    <i class="fa fa-file-o" aria-hidden="true"></i> Mon document de projet
                </a>
            </h5>
        </div>
        <div id="step-3" class="">
            <div id="proposal-success-alert" style="display: none" class="alert alert-success" role="alert"></div>
            <div id="proposal-danger-alert" style="display: none" class="alert alert-danger" role="alert"></div>

            <button type="button" class="btn btn-prime btnNormal" data-url="@Url.Action("UpdateProposalStatus", "Proposal", new {proposalId = Model.ProposalId, userId = Model.UserId})" id="btnSendProposal">Envoyer propostion</button>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery.smartWizard.min.js"></script>
<script src="~/Scripts/Proposal/proposal-wizard.js"></script>

Portalia/Views/Proposal/_Documents.cshtml
@using Microsoft.AspNet.Identity
@using Newtonsoft.Json
@using Portalia.Core.Enum
@model Portalia.ViewModels.DocumentViewModel


<div class="row">
    <div class="col-sm-12">
        @if ((User.IsInRole("Administrator") || Model.FolderType == FolderType.Other || Model.FolderType == FolderType.MyProject) && Model.FolderType != FolderType.MyOpportunities)
        {
            <a class="btn btn-outline top10" id="upload-document" data-url="@Url.Action("UploadDocumentForUser", "Proposal", new {userId = Model.UserId, proposalId = Model.ProposalId, folderType = Model.FolderType})">@Portalia.Resources.Proposal.CreateNewDocument</a>
        }
    </div>
</div>
<div class="row row-fluid top10 documents">
    <div class="col-sm-12">
        @if (Model.FolderType != FolderType.MyOpportunities)
        {
            <table class="table table-hover">
                <tbody>
                    <tr>
                        @if (Model.FolderType == FolderType.MyProject)
                        {
                            <td colspan="3">
                                <i class="fa fa-file"></i><a target="_blank" rel="noopener" href="~/Content/Proposal/ProjectProposal.pdf">Project proposal document</a>
                            </td>
                        }
                    </tr>
                    @foreach (var document in Model.Documents)
                    {
                        <tr>
                            <td>
                                <i class="fa fa-file"></i>
                                @if (!document.ProposalId.HasValue)
                                {
                                    <a target="_black" href="@Url.Action("DownloadDefault", new {document.DocumentId})"> @document.Name</a>
                                }
                                else
                                {
                                    <a target="_black" href="@Url.Action("Download", new {document.DocumentId, userId = Model.UserId})"> @document.Name</a>
                                }
                            </td>
                            <td>@document.CreatedDate.ToShortDateString()</td>
                            @if ((User.IsInRole("Administrator") || Model.FolderType == FolderType.Other || Model.FolderType == FolderType.MyProject) && (document.ProposalId.HasValue))
                            {
                                <td>
                                    <a href="#" data-url-delete="@Url.Action("DeleteDocument", "Document")" data-document="@JsonConvert.SerializeObject(document)" class="delete-document btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {

            <a target="_black" href="https://www.littlebigconnection.com/fr/">
                <img src="https://cdn.o2f-it.com/16387/littlebigicon_JPG" />
            </a>

        }
    </div>
</div>


<script src="~/Scripts/DocumentManagement/document-management.js"></script>

Portalia/Views/Proposal/_SendProposal.cshtml
@using Microsoft.AspNet.Identity
@using Portalia.Core.Enum
@using Portalia.ViewModels
@model Portalia.Core.Entity.Proposal
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Send Proposal: @Model.ClientName</h4>
</div>
<div class="modal-body">
    <h4>Client: @Model.ClientName</h4>
    <h4>Project: @Model.ProjectName</h4>
    <p>@Model.Description</p>
    <p>Template <a href="http://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt"><i class="fa fa-file"></i></a></p>
    @Html.Partial("_FileUpload", new FileUploadViewModel
{
    UrlAction = Url.Action("UploadFile", "Document", new { folderType = FolderType.MyContract, proposalId = Model.ProposalId,userId=Model.UserId })
})
    <div class="alert alert-warning" id="messageContent" style="display: none">
        <strong>Warning!</strong> Indicates a warning that might need attention.
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
    <button type="button" class="btn btn-prime btnNormal" data-url="@Url.Action("UpdateProposalStatus", "Proposal", new { proposalId = Model.ProposalId })" id="btnSendProposal">Envoyer proposition</button>
</div>

Portalia/Views/Proposal/_UploadDocumentForUser.cshtml
@using Microsoft.AspNet.Identity
@using Portalia.Core.Enum
@using Portalia.ViewModels
@model UserDocumentViewModel
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Télécharger des fichiers</h4>
</div>
<div class="modal-body">
    @Html.Partial("_FileUpload", new FileUploadViewModel
{
    UrlAction = Url.Action("UploadFile", "Document",new { userId = Model.UserId, proposalId = Model.ProposalId, folderType = Model.FolderType})
})
    <div class="alert alert-warning" id="messageContent" style="display: none">
        <strong>Attention!</strong> Indicates a warning that might need attention.
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
</div>